export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const CONTACT_GETT_REQUEST = 'CONTACT_GETT_REQUEST'
export const CONTACT_GETT_SUCCESS = 'CONTACT_GETT_SUCCESS'
export const CONTACT_GETT_FAILED = 'CONTACT_GETT_FAILED'

export const CONTACT_ADD_REQUEST = 'CONTACT_ADD_REQUEST';
export const CONTACT_ADD_SUCCESS = 'CONTACT_ADD_SUCCESS';
export const CONTACT_ADD_FAILED = 'CONTACT_ADD_FAILED';

export const CONTACT_DELETE_REQUEST = 'CONTACT_DELETE_REQUEST';
export const CONTACT_DELETE_SUCCESS = 'CONTACT_DELETE_SUCCESS';
export const CONTACT_DELETE_FAILED = 'CONTACT_DELETE_FAILED';

export const CONTACT_RENAME_REQUEST = 'CONTACT_RENAME_REQUEST';
export const CONTACT_RENAME_SUCCESS = 'CONTACT_RENAME_SUCCESS';
export const CONTACT_RENAME_FAILED = 'CONTACT_RENAME_FAILED';